<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="example0.css"?>
<!DOCTYPE students[
        <!ENTITY desc "学生信息说明">
        <!ELEMENT students (id,name,age,gender,desc,br)+>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT desc (#PCDATA)>
        <!ELEMENT br EMPTY>
        ]>
<students>
    <id>00110</id>
    <name>张三</name>
    <age><![CDATA[原样输出的方式]]></age>
    <gender>男</gender>
    <desc>&lt;&desc;&gt;</desc>
    <br/>
    <id>00111</id>
    <name>lisi</name>
    <age><![CDATA[原样输出的方式]]></age>
    <gender>女</gender>
    <desc>&lt;&desc;&gt;</desc>
    <br/>
</students>