=== IT-Qsg/project/xmlProject/out/production/xmlProject/lut/day3/homework/class_info.dtd
<!ELEMENT class-infomation (class+))>

        <!ELEMENT class (persion-num,gender+,hosts)>

        <!ATTLIST class id ID #REQUIRED>

        <!ELEMENT persion-num (#PCDATA)>

        <!ELEMENT gender (number)>

        <!ELEMENT number (#PCDATA)>

        <!ATTLIST number type (男|女) #REQUIRED>

        <!ELEMENT hosts (host)>

        <!ELEMENT host (start-host-num,end-host-num)>

        <!ATTLIST host gender (男|女) #REQUIRED>

        <!ELEMENT start-host-num (#PCDATA)>

        <!ELEMENT end-host-num (#PCDATA)>

=== IT-Qsg/project/xmlProject/out/production/xmlProject/lut/day3/homework/class_info.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE class-infomation SYSTEM "class_info.dtd">
<class-infomation>
    <class id="1001">
        <persion-num>30</persion-num>
        <gender>
            <number type="女">10</number>
            <number type="男">20</number>
        </gender>
        <hosts>
            <host gender="男">
                <start-host-num>A301</start-host-num>
                <end-host-num>A304</end-host-num>
            </host>
            <host gender="女">
                <start-host-num>B202</start-host-num>
                <end-host-num>B203</end-host-num>
            </host>
        </hosts>
    </class>
    <class id="1002">
        <persion-num>30</persion-num>
        <gender>
            <number type="女">10</number>
            <number type="男">20</number>
        </gender>
        <hosts>
            <host gender="男">
                <start-host-num>A301</start-host-num>
                <end-host-num>A304</end-host-num>
            </host>
            <host gender="女">
                <start-host-num>B202</start-host-num>
                <end-host-num>B203</end-host-num>
            </host>
        </hosts>
    </class>
</class-infomation>
